apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nemesis-crab
resources:
  - namespace.yml
  - configmap.yml
  - secret.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - hpa.yml
  - networkpolicy.yml
commonLabels:
  app.kubernetes.io/name: nemesis-crab-v2
  app.kubernetes.io/version: "2.0.0"
images:
  - name: registry.gitlab.com/your-org/nemesis-crab-v2
    newTag: latest
