apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemesis-data-pvc
  namespace: nemesis-crab
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemesis-reports-pvc
  namespace: nemesis-crab
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
