apiVersion: v1
kind: Secret
metadata:
  name: nemesis-secrets
  namespace: nemesis-crab
type: Opaque
stringData:
  WEB_SECRET_KEY: "change-me-in-production"
  WEB_ADMIN_PASSWORD: "change-me"
  DISCORD_TOKEN: ""
  TELEGRAM_TOKEN: ""
  SLACK_TOKEN: ""
  REDIS_PASSWORD: "nemesis_redis_pass"
  POSTGRES_PASSWORD: "nemesis_pg_pass"
